name:                TwitterClone
version:             0.1.0.0
github:              "kdabi/TwitterClone"
license:             BSD3
author:              "Kritagya Ishika"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/TwitterClone#readme>

dependencies:
- aeson
- base >= 4.7 && < 5
- blaze-html
- bytestring
- conduit
- containers
- happstack-hsp
- happstack-jmacro
- happstack-server
- hsp >=0.9 && < 0.11
- hsx2hs
- hsx-jmacro
- HTTP
- jmacro
- mongoDB
- mtl >=2.0 && <2.3
- network
- persistent
- persistent-sqlite
- persistent-template
- random
- sqlite-simple
- transformers

library:
  source-dirs: src

executables:
  TwitterClone-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - TwitterClone

tests:
  TwitterClone-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - TwitterClone
